name: publish

permissions:
  contents: write

on:
  push:
    tags:
    - '*' 

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 24.7.0

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command

      - name: Build
        uses: borales/actions-yarn@v5
        with:
          cmd: build

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          name: Auto Release
          tag_name: ${{ github.ref }}
          body: Auto Release
          draft: false
          prerelease: false
          files: dist/*

      # - uses: wdzeng/chrome-extension@v1
      #   with:
      #     extension-id: lgncmpklmepncbjpiebhdoejhmbcnjad
      #     zip-path: dist/Maple.zip
      #     tester-only: false
      #     client-id: ${{ secrets.CHROME_CLIENT_ID }}
      #     client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
      #     refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
